### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by oDevBR** [whisoer/spotify-radio#2]
- [ ] disponibilizar um novo efeito
- [ ] adicionar um botão novo no controlador
- [ ] adicionar um som de efeito novo para a pasta `audios/fx/`
- [ ] republicar no heroku
